version: '3'
services:
    mssql:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: mssql01
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@sswOrd123
        - MSSQL_PID=Express
        - MSSQL_LCID=1041
        - MSSQL_COLLATION=Japanese_CI_AS
      volumes:
        - "/var/lib/docker/volumes/sql1-vol/_data"
